root: true

extends:
  - 'standard-with-typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:svelte/recommended'

plugins: ['@typescript-eslint']

parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2020
  extraFileExtensions: ['.svelte']

env:
  browser: true
  es2017: true
  node: true

overrides:
  - files: ['*.svelte']
    parser: 'svelte-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
