dist: trusty
language: node_js
node_js:
  - node
  - lts/*
addons:
  sonarcloud:
    organization: "ctrlaltdev-github"
    token:
      secure: "mgXlPYO8L3+Y+jEX6UJ4htFeXzHddaMUix9kt6pQdFjLj83fnKw9xYp75eApTKdOF+zPoFWhM74P78vqhMPeSYvHdX/W532B9B4l/+bwtksn/aHIaUlQFH592vQQ/RPCuxUrXnKZKqOYwzDL0H+AD0Dt0pp5uYLQafLPMgHSJKVvpGbrrFoWj0qSKXOmUfCZHEmyhBIE9G77VriqEdcpQCMo/0OfD8B1nj1tk+RpQQmHrJQxOazvLIyEyPiJXiy3EAepcufUUCh2OZIMwI4IyHnJC2nRmgCX4TFUkMC2asmsf45lSWW6QdQGfYFDsOz7tYSvAgUS4OVuWgWIhDHaBuC2OyP5h6uEB9iASV1laXN0U6TYdNr76846jdx7MqqRIboGBy1F0+ZlbBHsnhP+oeMZw26Gdb6GsaCYYsK2H1PhKrkPaj9aFDNKLffDRfU2ADK/dQMRRHcNFJsJTQ8WT8HBWRoCT8YfxAFItPNlMpbN7E7MkyOkacwSKwuoRFrgXwWAWzDdrWaR+a/fpURfvz9AQk2jyI2tmtdXElBuzA0sj1N8Vbem8nuFhZlKegq6rB0z7Uo9oajW3IgsPx0t006m0ROf06AHjaCibuV9cqrRGgDA0CU13hVxsA79z+ULCvWPU8/9MmKANGUV2gKNbf3uF1jIBwrc2N1ZFvR9SRo="
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  fqdn: ctrlaltdev.xyz
  on:
    branch: master
before_script:
  - yarn run build
script:
  - yarn test --coverage
  - sonar-scanner
cache:
  directories:
    - node_modules
    - '$HOME/.sonar/cache'
