name: build
on:
  push:
    branches:
      - master
env:
  NEXT_TELEMETRY_DEBUG: 1
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
jobs:
  build-deploy:
    name: Build, Export and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: export
        run: npm run export
      - name: upload
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: az storage blob upload-batch -d ${{ secrets.AZURE_CONTAINER }} -s ./out/
