name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Use Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm

    - name: Install Dependencies
      run: pnpm install

    - name: Check
      run: pnpm check

    - name: Build
      run: pnpm build

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Upload files
      run: |
        aws s3 sync ./build/ s3://ctrlalt.dev/ --delete

    - name: Invalidate Cache
      run: |
        aws cloudfront create-invalidation --distribution-id EFMJC4GLPUI1A --paths "/*"
