name: test
on: push
env:
  NEXT_TELEMETRY_DEBUG: 1
jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm i
      - name: lint
        run: npm run lint
